keys:
  - &users:
    - &roshan 525EB147DC227E358E3762DFE726000EF5F8FDB4
  - &hosts:
    - &juno age14n8nkhshqrumed9zgar50um6smjhu3eglnep9cktdy3pn59uev8qzgvapq
    - &razer age157vefeppmvahmv03ta4j4pjek0dyet6avj9ht8pwh3h0xscdqdgs6pvlk6
    - &alienware age14uegztkvt0hcykm3q3vhwglzhg2rzyg2wln67z3nnr4s59z4wd3qaylpxd

creation_rules:
  - path_regex: hosts/razer/secrets\.ya?ml$
    key_groups:
    - age:
      - *razer
      pgp:
      - *roshan
  - path_regex: hosts/juno/secrets\.ya?ml$
    key_groups:
    - age:
      - *juno
      pgp:
      - *roshan
  - path_regex: hosts/alienware/secrets\.ya?ml$
    key_groups:
    - age:
      - *alienware
      pgp:
      - *roshan
  - path_regex: hosts/common/secrets\.ya?ml$
    key_groups:
    - age:
      - *razer
      - *juno
      - *alienware
      pgp:
      - *roshan
